### ISSUE TITLE
Unable to Arm alarm

### ISSUE THREAD

**Issue by booshtukka** [K1LL3R234/homebridge-texecom#11]
I'm unable to Arm alarm. All the motion sensors are working correctly, so I believe the connection is working fine? This is awesome.

But the House Alarm either shows as Updating… or No Response. It did show up briefly as "Off" but then when I try to arm it it just says "Arming…" and nothing happens.

**Comment by booshtukka** [comment]
Okay, I've figured this out. I wasn't using the UDL code - I've entered that and now it works.

There's a definite delay between arming the system via the keypad and it showing up in Home. And if the alarm is triggered it's an even longer delay for that to show up. In HomeKit the critical alert showed, but a few minutes later - and the noise was not very loud! Is this all expected behaviour?

**Comment by K1LL3R234** [comment]
Hi yes you will need the UDL ;) If you do not interact on the home app and arm and disarm the system with keypad or keyswitch it should be relatively quick almost instant, same goes for triggering.

The moment you use it with the app the panel goes into a timeout state where it will not report for a time period. I think a max of 1min this is how the panels operate so that there is not missed communication, and that is why there is a delay that you see.

I hope it makes sense.
Feel free to ask more questions. I will try and help.

**Comment by K1LL3R234** [comment]
No problem doing my best. Trying to get it verified as well for the new homebridge. And will add some more features as I go along. If you have any recommendations please add them. And will try to add them.
